feat: remove/migrate target group elementary school
mint-vernetzt/community-platform pull request #1004
Opened 2023-08-24 13:23 UTC by manuelportela

Beware!: check with **local** supabase

run
$ npx ts-node prisma/scripts/update-targetgroups/index.ts

after migration the targetGroup is removed from base data import, so reseeding won't refill this option
(for testing probably keep "Grundschule" to reseed)

2023-08-28 08:02 UTC, phollome requested changes

2023-08-28 08:02 UTC, phollome commented on prisma/scripts/update-targetgroups/index.ts
> +  projectsWithElementarySchool.forEach(async (project) => {
@manuelportela This is not a propper way to do async in a loop. Use `await Promse.all` with a `.map` or `for await`.

2023-08-29 16:25 UTC, manuelportela commented
@phollome I've updated my solution and would like to ask you to offer another review.

kindest regards

2023-08-30 06:29 UTC, phollome approved these changes
🚀

2023-08-30 06:30 UTC, merged