feat: settings for speaker
mint-vernetzt/community-platform pull request #349
Opened 2022-08-30 11:57 UTC by phollome

## List issues that are affected

#314 

- [x] Tests

2022-08-30 15:06 UTC, nac62116 requested changes

2022-08-30 15:06 UTC, nac62116 commented on app/routes/event/$slug/settings/speakers/add-speaker.spec.tsx
> +
Duplicate tests "authenticated user" and "not privileged user"

2022-08-30 15:06 UTC, nac62116 commented on app/routes/event/$slug/settings/speakers/remove-speaker.spec.tsx
> +
Duplicate Tests "authenticated user" and "not privileged user"

2022-08-30 15:12 UTC, nac62116 commented
Nice one! Only found the duplicate tests. The rest looks superb! 🚀 

One last question:

What feels better concerning the nested routes?
- Working with an <Outlet> and defining the add/remove forms inside the child routes (see organization/settings/team)
- ...or working with only one index function inside the parent route and only outsourcing the action function (like you did here)

2022-08-31 07:00 UTC, phollome commented
@nac62116 I've removed the duplicate tests. 👍

It feels better to have the forms in one route and just outsource the actions of the forms. Having forms in the action routes confused me this time. 😊 I've linked the question to refactoring/discussion issue #337.

2022-08-31 08:44 UTC, nac62116 approved these changes
Nice one 🏎️

2022-08-31 08:44 UTC, merged